import {
  GUIDED_LESSON_SCHEMA_VERSION,
  type GuidedLessonDefinition,
} from "./contracts";

const ELARION = "hostfall.core/pact_of_elarion";
const GRAVELESS = "hostfall.core/uprising_of_the_graveless";

const elarionCard = (id: string) => `${ELARION}/${id}`;
const gravelessCard = (id: string) => `${GRAVELESS}/${id}`;

/**
 * First Seed, opening section. It deliberately stops before the Host awakens so its novice-facing
 * Preparation pacing can be reviewed before combat teaching is appended.
 */
export const FIRST_SEED_LESSON: GuidedLessonDefinition = {
  schemaVersion: GUIDED_LESSON_SCHEMA_VERSION,
  id: "first-seed",
  revision: 2,
  mode: "required",
  startStepId: "explain-objective",
  scenario: {
    seed: "first-seed-preparation-v2",
    playerDeckKey: ELARION,
    hostDeckKey: GRAVELESS,
    difficulty: "normal",
    activeSide: "player",
    phase: "main",
    turnNumber: 1,
    hostTurnNumber: 0,
    setupTurnsTotal: 3,
    setupTurnsRemaining: 3,
    setupCompletePendingHost: false,
    openingHandAccepted: true,
    mulligansTaken: 0,
    player: {
      life: 50,
      availableEnergy: 0,
      storedEnergy: 0,
      pendingStoredEnergy: 0,
      energyActionUsedThisTurn: false,
      lifePaidThisTurn: 0,
      lifeLostThisTurn: 0,
    },
    host: { poisonCounters: 0 },
    zones: {
      openingDeal: ["first_source", "second_source", "liora", "vaelor"],
      playerArchiveTopToBottom: ["maela", "heirs_shield"],
      playerField: [],
      playerMemory: [],
      playerOblivion: [],
      hostArchiveTopToBottom: [
        "host_archive_one",
        "host_archive_two",
        "host_archive_three",
        "host_archive_four",
        "host_archive_five",
        "host_archive_six",
      ],
      hostField: [],
      hostMemory: [],
      hostOblivion: [],
    },
    combat: { playerAttackers: [], hostAttackers: [], blockers: {} },
  },
  cards: {
    first_source: { cardKey: elarionCard("river_of_elarion") },
    second_source: { cardKey: elarionCard("river_of_elarion") },
    liora: { cardKey: elarionCard("liora_keeper_of_the_grove") },
    vaelor: { cardKey: elarionCard("vaelor_emerald_guardian") },
    maela: { cardKey: elarionCard("maela_watcher_of_the_heights") },
    heirs_shield: { cardKey: elarionCard("shield_of_the_heir") },
    host_archive_one: { cardKey: gravelessCard("graveless_soldier") },
    host_archive_two: { cardKey: gravelessCard("graveless_soldier") },
    host_archive_three: { cardKey: gravelessCard("graveless_soldier") },
    host_archive_four: { cardKey: gravelessCard("graveless_soldier") },
    host_archive_five: { cardKey: gravelessCard("graveless_soldier") },
    host_archive_six: { cardKey: gravelessCard("graveless_soldier") },
  },
  steps: [
    {
      id: "explain-objective",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.objectiveTitle", bodyKey: "guided.firstSeed.objectiveBody" },
      highlights: [{ kind: "surface", anchor: "host.archive" }],
      preconditions: [{ kind: "setup.remaining", amount: 3 }],
      nextStepId: "explain-preparation",
    },
    {
      id: "explain-preparation",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.preparationTitle", bodyKey: "guided.firstSeed.preparationBody" },
      highlights: [{ kind: "surface", anchor: "setup.progress" }],
      nextStepId: "review-opening-hand",
    },
    {
      id: "review-opening-hand",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.openingHandTitle", bodyKey: "guided.firstSeed.openingHandBody" },
      highlights: [{ kind: "surface", anchor: "player.hand" }],
      nextStepId: "play-first-source",
    },
    {
      id: "play-first-source",
      kind: "act",
      copy: { titleKey: "guided.firstSeed.firstSourceTitle", bodyKey: "guided.firstSeed.firstSourceBody" },
      highlights: [
        { kind: "card", alias: "first_source", role: "origin" },
        { kind: "surface", anchor: "player.field", role: "destination" },
      ],
      allowedIntent: { kind: "card.play", cardAlias: "first_source" },
      preconditions: [
        { kind: "setup.remaining", amount: 3 },
        { kind: "card.inZone", cardAlias: "first_source", side: "player", zone: "hand" },
      ],
      nextStepId: "observe-first-source",
    },
    {
      id: "observe-first-source",
      kind: "observe",
      copy: { titleKey: "guided.firstSeed.sourceEnteringTitle", bodyKey: "guided.firstSeed.sourceEnteringBody" },
      highlights: [{ kind: "surface", anchor: "player.sources" }],
      expectedReceipt: { kind: "source.played", cardAlias: "first_source" },
      preconditions: [{ kind: "card.inZone", cardAlias: "first_source", side: "player", zone: "field" }],
      nextStepId: "explain-source-energy",
    },
    {
      id: "explain-source-energy",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.sourceEnergyTitle", bodyKey: "guided.firstSeed.sourceEnergyBody" },
      highlights: [{ kind: "surface", anchor: "player.sources" }],
      preconditions: [{ kind: "card.inZone", cardAlias: "first_source", side: "player", zone: "field" }],
      nextStepId: "compare-first-costs",
    },
    {
      id: "compare-first-costs",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.compareCostsTitle", bodyKey: "guided.firstSeed.compareCostsBody" },
      highlights: [{ kind: "surface", anchor: "player.sources" }],
      presentation: {
        kind: "cardComparison",
        cardAliases: ["liora", "vaelor"],
        emphasis: "energyCost",
      },
      nextStepId: "continue-first-preparation",
    },
    {
      id: "continue-first-preparation",
      kind: "act",
      copy: { titleKey: "guided.firstSeed.continueFirstTitle", bodyKey: "guided.firstSeed.continueFirstBody" },
      highlights: [{ kind: "surface", anchor: "phase.primaryAction" }],
      allowedIntent: { kind: "phase.continueSetup" },
      preconditions: [{ kind: "setup.remaining", amount: 3 }],
      nextStepId: "draw-maela",
    },
    {
      id: "draw-maela",
      kind: "observe",
      copy: { titleKey: "guided.firstSeed.drawMaelaTitle", bodyKey: "guided.firstSeed.drawMaelaBody" },
      highlights: [
        { kind: "surface", anchor: "player.archive", role: "origin" },
        { kind: "surface", anchor: "player.hand", role: "destination" },
      ],
      expectedReceipt: { kind: "player.drew", targetAliases: ["maela"], amount: 1, reason: "setup" },
      nextStepId: "begin-second-preparation",
    },
    {
      id: "begin-second-preparation",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.secondPreparationTitle", bodyKey: "guided.firstSeed.secondPreparationBody" },
      highlights: [
        { kind: "surface", anchor: "setup.progress" },
        { kind: "card", alias: "maela" },
      ],
      preconditions: [
        { kind: "setup.remaining", amount: 2 },
        { kind: "card.inZone", cardAlias: "maela", side: "player", zone: "hand" },
      ],
      nextStepId: "play-second-source",
    },
    {
      id: "play-second-source",
      kind: "act",
      copy: { titleKey: "guided.firstSeed.secondSourceTitle", bodyKey: "guided.firstSeed.secondSourceBody" },
      highlights: [
        { kind: "card", alias: "second_source", role: "origin" },
        { kind: "surface", anchor: "player.field", role: "destination" },
      ],
      allowedIntent: { kind: "card.play", cardAlias: "second_source" },
      nextStepId: "observe-second-source",
    },
    {
      id: "observe-second-source",
      kind: "observe",
      copy: { titleKey: "guided.firstSeed.sourceEnteringTitle", bodyKey: "guided.firstSeed.sourceEnteringBody" },
      highlights: [{ kind: "surface", anchor: "player.sources" }],
      expectedReceipt: { kind: "source.played", cardAlias: "second_source" },
      preconditions: [{ kind: "card.inZone", cardAlias: "second_source", side: "player", zone: "field" }],
      nextStepId: "explain-liora-affordable",
    },
    {
      id: "explain-liora-affordable",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.lioraAffordableTitle", bodyKey: "guided.firstSeed.lioraAffordableBody" },
      highlights: [
        { kind: "surface", anchor: "player.sources" },
        { kind: "card", alias: "liora" },
      ],
      preconditions: [{ kind: "setup.remaining", amount: 2 }],
      nextStepId: "play-liora",
    },
    {
      id: "play-liora",
      kind: "act",
      copy: { titleKey: "guided.firstSeed.playLioraTitle", bodyKey: "guided.firstSeed.playLioraBody" },
      highlights: [
        { kind: "card", alias: "liora", role: "origin" },
        { kind: "surface", anchor: "player.field", role: "destination" },
      ],
      allowedIntent: { kind: "card.play", cardAlias: "liora" },
      nextStepId: "observe-liora-entry",
    },
    {
      id: "observe-liora-entry",
      kind: "observe",
      copy: { titleKey: "guided.firstSeed.echoEnteringTitle", bodyKey: "guided.firstSeed.echoEnteringBody" },
      highlights: [{ kind: "surface", anchor: "player.field" }],
      expectedReceipt: { kind: "card.played", cardAlias: "liora" },
      preconditions: [{ kind: "card.inZone", cardAlias: "liora", side: "player", zone: "field" }],
      nextStepId: "explain-energy-spent",
    },
    {
      id: "explain-energy-spent",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.energySpentTitle", bodyKey: "guided.firstSeed.energySpentBody" },
      highlights: [
        { kind: "surface", anchor: "player.sources" },
        { kind: "card", alias: "maela" },
        { kind: "card", alias: "vaelor" },
      ],
      preconditions: [{ kind: "card.inZone", cardAlias: "liora", side: "player", zone: "field" }],
      nextStepId: "explain-liora-stabilizing",
    },
    {
      id: "explain-liora-stabilizing",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.lioraStabilizingTitle", bodyKey: "guided.firstSeed.lioraStabilizingBody" },
      highlights: [{ kind: "card", alias: "liora" }],
      nextStepId: "continue-second-preparation",
    },
    {
      id: "continue-second-preparation",
      kind: "act",
      copy: { titleKey: "guided.firstSeed.continueSecondTitle", bodyKey: "guided.firstSeed.continueSecondBody" },
      highlights: [{ kind: "surface", anchor: "phase.primaryAction" }],
      allowedIntent: { kind: "phase.continueSetup" },
      preconditions: [{ kind: "setup.remaining", amount: 2 }],
      nextStepId: "draw-heirs-shield",
    },
    {
      id: "draw-heirs-shield",
      kind: "observe",
      copy: { titleKey: "guided.firstSeed.drawShieldTitle", bodyKey: "guided.firstSeed.drawShieldBody" },
      highlights: [
        { kind: "surface", anchor: "player.archive", role: "origin" },
        { kind: "surface", anchor: "player.hand", role: "destination" },
      ],
      expectedReceipt: { kind: "player.drew", targetAliases: ["heirs_shield"], amount: 1, reason: "setup" },
      nextStepId: "explain-energy-refreshed",
    },
    {
      id: "explain-energy-refreshed",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.energyRefreshedTitle", bodyKey: "guided.firstSeed.energyRefreshedBody" },
      highlights: [
        { kind: "surface", anchor: "setup.progress" },
        { kind: "surface", anchor: "player.sources" },
      ],
      preconditions: [
        { kind: "setup.remaining", amount: 1 },
        { kind: "card.inZone", cardAlias: "heirs_shield", side: "player", zone: "hand" },
      ],
      nextStepId: "explain-liora-ready",
    },
    {
      id: "explain-liora-ready",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.lioraReadyTitle", bodyKey: "guided.firstSeed.lioraReadyBody" },
      highlights: [{ kind: "card", alias: "liora" }],
      nextStepId: "activate-liora",
    },
    {
      id: "activate-liora",
      kind: "act",
      copy: { titleKey: "guided.firstSeed.activateLioraTitle", bodyKey: "guided.firstSeed.activateLioraBody" },
      highlights: [{ kind: "card", alias: "liora" }],
      allowedIntent: {
        kind: "ability.activate",
        cardAlias: "liora",
        abilityId: "liora_keeper_of_the_grove_gain_energy",
      },
      preconditions: [{ kind: "energy.stored", amount: 0 }],
      nextStepId: "explain-extra-energy",
    },
    {
      id: "explain-extra-energy",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.extraEnergyTitle", bodyKey: "guided.firstSeed.extraEnergyBody" },
      highlights: [
        { kind: "surface", anchor: "player.reserve" },
        { kind: "surface", anchor: "player.sources" },
        { kind: "card", alias: "maela" },
      ],
      preconditions: [{ kind: "energy.stored", amount: 1 }],
      nextStepId: "play-maela",
    },
    {
      id: "play-maela",
      kind: "act",
      copy: { titleKey: "guided.firstSeed.playMaelaTitle", bodyKey: "guided.firstSeed.playMaelaBody" },
      highlights: [
        { kind: "card", alias: "maela", role: "origin" },
        { kind: "surface", anchor: "player.field", role: "destination" },
      ],
      allowedIntent: { kind: "card.play", cardAlias: "maela" },
      preconditions: [{ kind: "energy.stored", amount: 1 }],
      nextStepId: "observe-maela-entry",
    },
    {
      id: "observe-maela-entry",
      kind: "observe",
      copy: { titleKey: "guided.firstSeed.echoEnteringTitle", bodyKey: "guided.firstSeed.echoEnteringBody" },
      highlights: [{ kind: "surface", anchor: "player.field" }],
      expectedReceipt: { kind: "card.played", cardAlias: "maela" },
      preconditions: [{ kind: "card.inZone", cardAlias: "maela", side: "player", zone: "field" }],
      nextStepId: "explain-maela-skyguard",
    },
    {
      id: "explain-maela-skyguard",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.maelaSkyguardTitle", bodyKey: "guided.firstSeed.maelaSkyguardBody" },
      highlights: [{ kind: "card", alias: "maela" }],
      preconditions: [
        { kind: "card.inZone", cardAlias: "maela", side: "player", zone: "field" },
        { kind: "energy.stored", amount: 0 },
      ],
      nextStepId: "preparation-ready",
    },
    {
      id: "preparation-ready",
      kind: "explain",
      copy: { titleKey: "guided.firstSeed.readyTitle", bodyKey: "guided.firstSeed.readyBody" },
      highlights: [
        { kind: "surface", anchor: "setup.progress" },
        { kind: "card", alias: "liora" },
        { kind: "card", alias: "maela" },
      ],
    },
  ],
};
