export const UI_FEATURE_FLAGS = {
  alignHdHandActionSweep: true,
  renderHdHandCardsAsHtml: false,
  renderHtmlBattlefieldHoverPreviews: true,
  renderHtmlDeckPreviews: true,
  renderHtmlMulliganCards: true,
  renderHtmlRightClickPreviews: true,
  renderHtmlHandAtHoverResolution: true,
  isolateHtmlHandActionableGlow: true,
  isolateHtmlHandActionableSweep: true,
  showDynamicHandCardStats: false,
  stabilizeHtmlMulliganHoverText: true,
  useAdjustedPlayerHandCardHoverScale: true,
  useLargerPlayerHandCards: true,
  useLocalExactCardFonts: true,
  useNativeHdHandImageRendering: true,
} as const;
