export const UI_REFERENCE_GROUPS = [
  "Fundamentos",
  "Navegación y ajustes",
  "Mazos y cartas",
  "Tablero y HUD",
  "Modales y diálogos",
  "Overlays y feedback",
  "Tutorial",
  "Resultados",
] as const;

export type UiReferenceGroup = (typeof UI_REFERENCE_GROUPS)[number];
export type UiReferenceStatus = "canonical" | "product-variant" | "context-only";

export type UiReferenceEntry = Readonly<{
  id: string;
  group: UiReferenceGroup;
  component: string;
  source: string;
  usedIn: readonly string[];
  status: UiReferenceStatus;
  specimen?: string;
}>;

/**
 * Executable UI inventory. Every entry below is reachable from the player runtime in `src/`.
 * Mockups, VFX, developer tools and exports without a runtime consumer are deliberately absent.
 */
export const UI_REFERENCE_CATALOG: readonly UiReferenceEntry[] = [
  {
    id: "ui-primitives",
    group: "Fundamentos",
    component: "Hostfall UI primitives (`hf-ui-*`)",
    source: "src/ui-system.css",
    usedIn: ["Paneles, títulos y controles compartidos de la UI activa", "Portales y superficies aisladas del tablero"],
    status: "canonical",
    specimen: "foundations",
  },
  {
    id: "loading-screen",
    group: "Navegación y ajustes",
    component: "GameLoadingScreen",
    source: "src/components/GameLoadingScreen.tsx",
    usedIn: ["Arranque de la aplicación", "Transición de entrada y salida de una Visión"],
    status: "product-variant",
  },
  {
    id: "error-boundary",
    group: "Navegación y ajustes",
    component: "AppErrorBoundary",
    source: "src/components/AppErrorBoundary.tsx",
    usedIn: ["Fallback raíz del renderer"],
    status: "context-only",
  },
  {
    id: "start-menu",
    group: "Navegación y ajustes",
    component: "StartMenu",
    source: "src/components/StartMenu.tsx",
    usedIn: ["Home", "Umbral de Jugar", "Preparar un Futuro", "Chaos", "Crónicas", "Huestes", "Cómo jugar", "Ajustes"],
    status: "product-variant",
  },
  {
    id: "play-threshold",
    group: "Navegación y ajustes",
    component: "PlayThreshold",
    source: "src/components/PlayThreshold.tsx",
    usedIn: ["Home → Jugar → preparar un Futuro o introducir una Inscripción"],
    status: "context-only",
  },
  {
    id: "chronicler-name-modal",
    group: "Modales y diálogos",
    component: "ChroniclerNameModal",
    source: "src/components/StartMenu.tsx",
    usedIn: ["Primer arranque → reclamar nombre", "Home → editar identidad del Cronista"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "setup-deck-drawer",
    group: "Modales y diálogos",
    component: "SetupDeckDrawer",
    source: "src/components/StartMenu.tsx",
    usedIn: ["Preparar un Futuro → Cambiar Crónica", "Preparar un Futuro → Cambiar Hueste"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "settings-controls",
    group: "Navegación y ajustes",
    component: "LanguageSelector · AudioControls · DisplayControls · VolumePercentInput",
    source: "src/components/{LanguageSelector,AudioControls,DisplayControls,VolumePercentInput}.tsx",
    usedIn: ["Menú principal → Ajustes", "Visión → Ajustes → General/Audio"],
    status: "canonical",
    specimen: "settings-controls",
  },
  {
    id: "app-header",
    group: "Tablero y HUD",
    component: "AppHeader",
    source: "src/components/AppHeader.tsx",
    usedIn: ["Cabecera superior de Board"],
    status: "product-variant",
  },
  {
    id: "music-player-menu",
    group: "Navegación y ajustes",
    component: "MusicPlayerMenu",
    source: "src/components/MusicPlayerMenu.tsx",
    usedIn: ["Board → AppHeader → Música"],
    status: "product-variant",
  },
  {
    id: "destiny-copy-identity-button",
    group: "Navegación y ajustes",
    component: "DestinyCopyIdentityButton",
    source: "src/components/DestinyCopyIdentityButton.tsx",
    usedIn: ["Board normal → AppHeader → Copiar Inscripción"],
    status: "product-variant",
  },
  {
    id: "settings-menu-modal",
    group: "Modales y diálogos",
    component: "SettingsMenu",
    source: "src/components/SettingsMenu.tsx",
    usedIn: ["Board → AppHeader → Ajustes", "Escape durante una Visión", "Sesiones tutorial y Aprender a jugar"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "destiny-rewrite-dialog",
    group: "Modales y diálogos",
    component: "DestinyRewriteControl",
    source: "src/components/DestinyRewriteControl.tsx",
    usedIn: ["Board normal → comando Contemplar de nuevo"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "deck-key-card",
    group: "Mazos y cartas",
    component: "DeckKeyCard",
    source: "src/components/DecksView.tsx",
    usedIn: ["Menú → Crónicas/Huestes", "Preparar expedición → selector de mazo"],
    status: "canonical",
    specimen: "deck-key-card",
  },
  {
    id: "deck-navigation",
    group: "Mazos y cartas",
    component: "DecksView · DeckInspector",
    source: "src/components/{DecksView,DeckInspector}.tsx",
    usedIn: ["Colecciones de Crónicas y Huestes", "Detalle, búsqueda y lectura de un mazo"],
    status: "product-variant",
  },
  {
    id: "deck-inspector-details-modal",
    group: "Modales y diálogos",
    component: "DeckInspectorDetailsModal",
    source: "src/components/DeckInspector.tsx",
    usedIn: ["Crónicas/Huestes → DeckInspector → clic en una carta"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "card",
    group: "Mazos y cartas",
    component: "Card",
    source: "src/components/Card.tsx",
    usedIn: ["Mano", "Campo de batalla", "Mano inicial", "Targeting", "HUD y previews"],
    status: "canonical",
    specimen: "cards",
  },
  {
    id: "card-atoms",
    group: "Mazos y cartas",
    component: "CardCostBadge · CardStatsBadge · CardDefenseBadge · CardTraitIconBadges",
    source: "src/components/Card.tsx",
    usedIn: ["Card", "Comparaciones del tutorial", "Presentaciones de coste, stats y Rasgos"],
    status: "canonical",
    specimen: "card-atoms",
  },
  {
    id: "card-details",
    group: "Mazos y cartas",
    component: "CardPreview · PreviewStatsBadge · TraitPills",
    source: "src/components/CardPreview.tsx",
    usedIn: ["Hover/foco global de cartas", "Inspector de mazo", "Detalle de Memoria"],
    status: "canonical",
    specimen: "card-details-atoms",
  },
  {
    id: "graveyard-viewer-modal",
    group: "Modales y diálogos",
    component: "GraveyardViewerModal",
    source: "src/components/GraveyardViewerModal.tsx",
    usedIn: ["Pilas de Memoria del Cronista y la Hueste"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "graveyard-details-modal",
    group: "Modales y diálogos",
    component: "GraveyardDetailsModal",
    source: "src/components/GraveyardViewerModal.tsx",
    usedIn: ["Memoria → clic en una carta", "Registro de la Visión/GameLog → detalle de carta"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "board",
    group: "Tablero y HUD",
    component: "Board",
    source: "src/components/Board.tsx",
    usedIn: ["Visión normal", "Preparación", "Aprender a jugar", "Prueba de seed en tablero"],
    status: "context-only",
  },
  {
    id: "battlefield-hand",
    group: "Tablero y HUD",
    component: "Battlefield · Hand · Zone",
    source: "src/components/{Battlefield,Hand,Zone}.tsx",
    usedIn: ["Board → filas de permanentes de ambos bandos", "Board → Mano del Cronista"],
    status: "context-only",
  },
  {
    id: "turn-phase-hud",
    group: "Tablero y HUD",
    component: "TurnPhaseHud",
    source: "src/components/TurnPhaseHud.tsx",
    usedIn: ["Board → AppHeader → estado de turno/fase", "Preparación → progreso de turnos"],
    status: "canonical",
    specimen: "turn-phase-hud",
  },
  {
    id: "duel-hud",
    group: "Tablero y HUD",
    component: "DuelHud · PlayerLifePanel · PlayerArchiveForecast",
    source: "src/components/{DuelHud,PlayerArchiveForecast}.tsx",
    usedIn: ["Board → archivo/veneno de la Hueste", "Board → Memoria, Archivo y Vida del Cronista"],
    status: "context-only",
  },
  {
    id: "phase-controls",
    group: "Tablero y HUD",
    component: "PhaseOrb · PhaseBanner",
    source: "src/components/{PhaseOrb,PhaseBanner}.tsx",
    usedIn: ["Board → acción primaria de fase", "Board → aviso de cambio de fase/preparación"],
    status: "product-variant",
  },
  {
    id: "zones",
    group: "Tablero y HUD",
    component: "ZoneDrawer",
    source: "src/components/ZoneDrawer.tsx",
    usedIn: ["Visión → Ajustes → zonas del Cronista y la Hueste"],
    status: "canonical",
    specimen: "zone-drawer",
  },
  {
    id: "opening-hand",
    group: "Modales y diálogos",
    component: "OpeningHandOverlay · OpeningHandModal",
    source: "src/components/OpeningHandOverlay.tsx",
    usedIn: ["Board antes de aceptar o cambiar la mano inicial"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "hand-limit-modal",
    group: "Modales y diálogos",
    component: "HandLimitOverlay · HandLimitModal",
    source: "src/components/HandLimitOverlay.tsx",
    usedIn: ["Fin de fase → descarte obligatorio por límite de Mano"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "targeting-overlays",
    group: "Overlays y feedback",
    component: "CounterTargetingOverlay · SpellTargetingOverlay · TributeOfTheFourSorrowsSelectionOverlay",
    source: "src/components/{CounterTargetingOverlay,SpellTargetingOverlay,TributeOfTheFourSorrowsSelectionOverlay}.tsx",
    usedIn: ["Selección de objetivos y pagos durante Board"],
    status: "context-only",
  },
  {
    id: "tooltip",
    group: "Overlays y feedback",
    component: "GameTooltip",
    source: "src/components/GameTooltip.tsx",
    usedIn: ["Rasgos de carta", "Pilas de Memoria/Archivo", "PhaseOrb", "Tutorial y controles"],
    status: "canonical",
    specimen: "tooltip",
  },
  {
    id: "toast-stack",
    group: "Overlays y feedback",
    component: "ToastStack",
    source: "src/components/ToastStack.tsx",
    usedIn: ["Board", "StartMenu", "mensajes info/warning/success/danger/host"],
    status: "canonical",
    specimen: "toasts",
  },
  {
    id: "game-log",
    group: "Overlays y feedback",
    component: "GameLog",
    source: "src/components/GameLog.tsx",
    usedIn: ["Visión → Ajustes → registro y búsqueda de cartas"],
    status: "canonical",
    specimen: "game-log",
  },
  {
    id: "learn-intro",
    group: "Modales y diálogos",
    component: "LearnToPlayIntroModal · GuidedTutorialDialog",
    source: "src/components/{LearnToPlayIntroModal,GuidedTutorialDialog}.tsx",
    usedIn: ["Cómo jugar → Aprender a jugar → introducción"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "guided-tutorial-dialog",
    group: "Modales y diálogos",
    component: "GuidedTutorialDialog",
    source: "src/components/GuidedTutorialDialog.tsx",
    usedIn: ["Aprender a jugar → introducción narrativa", "GuidedTutorialOverlay → Preparación", "GuidedTutorialOverlay → Aprender a jugar → pasos estrictos"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "guided-tutorial-overlay",
    group: "Tutorial",
    component: "GuidedTutorialOverlay",
    source: "src/components/GuidedTutorialOverlay.tsx",
    usedIn: ["Preparación", "Aprender a jugar → pasos estrictos sobre Board"],
    status: "context-only",
  },
  {
    id: "contextual-tutorial-callout",
    group: "Tutorial",
    component: "ContextualTutorialCallout",
    source: "src/components/ContextualTutorialCallout.tsx",
    usedIn: ["Visión normal → ayuda contextual anclada al Board"],
    status: "context-only",
  },
  {
    id: "guided-support-ui",
    group: "Tutorial",
    component: "GuidedCardComparison · TutorialDirectionalCue · LearnToPlayJourneyCues",
    source: "src/components/{GuidedCardComparison,TutorialDirectionalCue,LearnToPlayJourneyCues}.tsx",
    usedIn: ["Preparación", "Aprender a jugar → comparaciones y pistas sobre Board"],
    status: "context-only",
  },
  {
    id: "game-confirmation-dialog",
    group: "Modales y diálogos",
    component: "GameConfirmationDialog",
    source: "src/components/GameConfirmationDialog.tsx",
    usedIn: ["Board → volver al menú", "Board → tutorial interrumpido", "SettingsMenu → confirmar reinicio"],
    status: "canonical",
    specimen: "modal-gallery",
  },
  {
    id: "game-outcome-dialog",
    group: "Resultados",
    component: "GameOutcomeDialog",
    source: "src/components/GameOutcomeDialog.tsx",
    usedIn: ["VictoryModal → veredicto de victoria", "DefeatModal → veredicto de derrota"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "learn-defeat-outcome-dialog",
    group: "Resultados",
    component: "LearnToPlayDefeatOutcomeDialog",
    source: "src/components/LearnToPlayDefeatDialogs.tsx",
    usedIn: ["Aprender a jugar → derrota pedagógica → veredicto"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
  {
    id: "learn-defeat-narrative-dialog",
    group: "Resultados",
    component: "LearnToPlayDefeatNarrativeDialog",
    source: "src/components/LearnToPlayDefeatDialogs.tsx",
    usedIn: ["Aprender a jugar → derrota pedagógica → explicación del Cronista"],
    status: "product-variant",
    specimen: "modal-gallery",
  },
] as const;
